# -*- coding: utf-8 -*-
"""T test FDSA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aPLfSrffiE_Sy3DAW8LuIMG9bKxMJMPU
"""

#Ztest using dataset

#import libraries
import pandas as pd
from statsmodels.stats import weightstats as stests

#Read CSV file
df = pd.read_csv(r"/content/diabetes.csv")
df.head()

#describe the valPetalLengthCmue
df[['Glucose','BMI']].describe()

#By using the Z-test in Stats
ztest ,propability_value = stests.ztest(df['Pregnancies'], x2=None, value=129)
print(float(propability_value))

#Hypothesis
if propability_value<0.05:
    print("Null hyphothes is rejected , Alternative hyphothesis accepted")
else:
    print("Null hyphothesis accepted , Alternative hyphothesis rejected")

#Two tail Z-test(using python inbuild function)
#Import libraries
from statsmodels.stats.weightstats import ztest as ztest

#entering a simple value
A = [82, 84, 85, 89, 91, 91, 92, 94, 99, 99,
         105, 109, 109, 109, 110, 112, 112, 113, 114, 114]

B = [90, 91, 91, 91, 95, 95, 99, 99, 108, 109,
         109, 114, 115, 116, 117, 117, 128, 129, 130, 133]

#perform two sample z-test
ztest(A, B, value=0)

#T-test(one sample)
#Import Python librarie
import numpy as np
from scipy import stats 
from numpy.random import seed
from numpy.random import randn
from numpy.random import normal
from scipy.stats import ttest_1samp



#Create a random sample group
seed=(1)
sample =normal(150,10,20)
print('Sample: ', sample)




#Conduct the test
t_stat, p_value = ttest_1samp(sample, popmean=155)
print("T-statistic value: ", t_stat)  
print("P-Value: ", p_value)
#Result
if p_value <= t_stat:
  print("Reject the null hypothesis")
else:
  print("Accept the null hypothesis")

#T-test(two-tailed test)
#Import libraries
from numpy.random import seed
from numpy.random import randn
from numpy.random import normal
from scipy.stats import ttest_ind




# seed the random number generator
seed(1)
# create two independent sample groups
sample1= normal(30, 16, 50)
sample2=normal(33, 18, 50)
print('Sample 1: ',sample1)
print('Sample 2: ',sample2)




#Conduct the test
t_stat, p_value = ttest_ind(sample1, sample2)
print("T-statistic value: ", t_stat)  
print("P-Value: ", p_value)




#Result
if p_value <= t_stat:
  print("Reject the null hypothesis")
else:
  print("Accept the null hypothesis")